version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"

    environment:
      - PERSON_MONGO_ADDR=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    hostname: mongodb-server
    image: mongo:3.4
    ports:
      - "27017:27017"
    restart: always